# Configuração do Flyway para o projeto Controle financeiro

# Localizações de migrations são definidas nos arquivos de configuração de ambiente
# (DEV, HML, PROD) ou na linha de comando do workflow.

# Define a codificação do arquivo de migration
flyway.encoding=UTF-8
# Valida se os nomes dos arquivos seguem o padrão correto
flyway.validateMigrationNaming=true
# Define o prefixo dos arquivos de migration
flyway.sqlMigrationPrefix=V
# Define os sufixos aceitos para arquivos de migration
flyway.sqlMigrationSuffixes=.sql
# Define o separador de versão nos arquivos de migration
flyway.sqlMigrationSeparator=__
# Registra quem realizou a migração
flyway.installedBy= ${MIGRATION_INSTALLED_BY}
# Bloqueia a execução do comando 'clean' para evitar perda acidentado de dados
flyway.cleanDisabled=true
# Controla se schemas devem ser criados automaticamente se não existirem
flyway.createSchemas=false
# Permitir que o flyway execute migrações fora de ordem (útil para migrações de correção)
flyway.outOfOrder=true

# Exemplo (definir nos arquivos de ambiente):
# flyway.locations=filesystem:sql/migrations/db/projects/controle-financeiro/admin/common,filesystem:sql/migrations/db/projects/controle-financeiro/admin/dev

