# Configuracao para criacao/gestao do usuario APPLICATION no ambiente DEV

# Conexao administrativa do ambiente DEV
flyway.url=${APP_DEV_ADMIN_URL}
flyway.user=${APP_DEV_ADMIN_USER}
flyway.password=${APP_DEV_ADMIN_PASSWORD}
flyway.jdbcProperties.internal_logon=SYSDBA
flyway.defaultSchema=${APP_DEV_ADMIN_USER}
flyway.table=flyway_history_app_dev

flyway.locations=filesystem:./sql/migrations/db/projects/controle-financeiro/admin/users/provision/app-dev

# Placeholders usados pelos scripts SQL do APPLICATION DEV
flyway.placeholders.usuario_nome=${APP_DEV_USER}
flyway.placeholders.usuario_senha=${APP_DEV_PASSWORD}
flyway.placeholders.default_tablespace=${APP_DEV_DEFAULT_TABLESPACE}
flyway.placeholders.temp_tablespace=${APP_DEV_TEMP_TABLESPACE}
