# Configuracao para validar migrations de estrutura no schema APPLICATION PROD

flyway.url=${APP_PROD_ADMIN_URL}
flyway.user=${APP_PROD_USER}
flyway.password=${APP_PROD_PASSWORD}
flyway.table=flyway_history_validacao_app_prod
flyway.locations=filesystem:./sql/migrations/db/projects/controle-financeiro/application/app-prod
flyway.placeholders.ambiente=${APP_PROD_DATABASE_NAME}

flyway.baselineOnMigrate=true
flyway.connectRetries=10
flyway.connectRetriesInterval=5
