# Configuracao para criacao/gestao do usuario OWNER no ambiente PROD

# Conexao administrativa do ambiente PROD
flyway.url=${OWNER_PROD_ADMIN_URL}
flyway.user=${OWNER_PROD_ADMIN_USER}
flyway.password=${OWNER_PROD_ADMIN_PASSWORD}
flyway.jdbcProperties.internal_logon=SYSDBA
flyway.defaultSchema=${OWNER_PROD_ADMIN_USER}
flyway.table=flyway_history_provision_owner_prod

flyway.locations=filesystem:./sql/migrations/db/projects/controle-financeiro/admin/users/provision/owner-prod
flyway.baselineOnMigrate=true
flyway.baselineVersion=0

# Placeholders usados pelos scripts SQL do OWNER PROD
flyway.placeholders.OWNER_PROD_USER=${OWNER_PROD_USER}
flyway.placeholders.OWNER_PROD_PASSWORD=${OWNER_PROD_PASSWORD}
flyway.placeholders.OWNER_PROD_DEFAULT_TABLESPACE=${OWNER_PROD_DEFAULT_TABLESPACE}
flyway.placeholders.OWNER_PROD_TEMP_TABLESPACE=${OWNER_PROD_TEMP_TABLESPACE}

