# Configuracao para validar migrations de estrutura no schema APPLICATION HML

flyway.url=${APP_HML_ADMIN_URL}
flyway.user=${APP_HML_USER}
flyway.password=${APP_HML_PASSWORD}
flyway.table=flyway_history_validacao_app_hml
flyway.locations=filesystem:./sql/migrations/db/projects/controle-financeiro/application/app-hml
flyway.placeholders.ambiente=${APP_HML_DATABASE_NAME}

flyway.baselineOnMigrate=true
flyway.connectRetries=10
flyway.connectRetriesInterval=5
