# Configuracao para criacao/gestao do usuario APPLICATION no ambiente PROD

# Conexao administrativa do ambiente PROD
flyway.url=${APP_PROD_ADMIN_URL}
flyway.user=${APP_PROD_ADMIN_USER}
flyway.password=${APP_PROD_ADMIN_PASSWORD}
flyway.jdbcProperties.internal_logon=SYSDBA
flyway.defaultSchema=${APP_PROD_ADMIN_USER}
flyway.table=flyway_history_app_prod

flyway.locations=filesystem:./sql/migrations/db/projects/controle-financeiro/application/app-prod

# Placeholders usados pelos scripts SQL do APPLICATION PROD
flyway.placeholders.usuario_nome=${APP_PROD_USER}
flyway.placeholders.usuario_senha=${APP_PROD_PASSWORD}
flyway.placeholders.default_tablespace=${APP_PROD_DEFAULT_TABLESPACE}
flyway.placeholders.temp_tablespace=${APP_PROD_TEMP_TABLESPACE}
