# Configuracao para validar migrations de estrutura no schema OWNER DEV

flyway.url=${OWNER_DEV_ADMIN_URL}
flyway.user=${OWNER_DEV_USER}
flyway.password=${OWNER_DEV_PASSWORD}
flyway.defaultSchema=${OWNER_DEV_USER}
flyway.table=flyway_history_validacao_owner_dev
flyway.locations=filesystem:./sql/migrations/db/projects/controle-financeiro/owner/owner-dev
flyway.placeholders.ambiente=${OWNER_DEV_DATABASE_NAME}

flyway.baselineOnMigrate=true
flyway.connectRetries=10
flyway.connectRetriesInterval=5
