# Configuracao para criacao/gestao do usuario APPLICATION no ambiente DEV

# Conexao administrativa do ambiente DEV
flyway.url=${APP_DEV_ADMIN_URL}
flyway.user=${APP_DEV_ADMIN_USER}
flyway.password=${APP_DEV_ADMIN_PASSWORD}
flyway.jdbcProperties.internal_logon=SYSDBA
flyway.defaultSchema=${APP_DEV_ADMIN_USER}
flyway.table=flyway_history_provision_app_dev

flyway.locations=filesystem:./sql/migrations/db/projects/controle-financeiro/admin/users/provision/app-dev
flyway.baselineOnMigrate=true
flyway.baselineVersion=0

# Placeholders usados pelos scripts SQL do APPLICATION DEV
flyway.placeholders.APP_DEV_USER=${APP_DEV_USER}
flyway.placeholders.APP_DEV_PASSWORD=${APP_DEV_PASSWORD}
flyway.placeholders.APP_DEV_DEFAULT_TABLESPACE=${APP_DEV_DEFAULT_TABLESPACE}
flyway.placeholders.APP_DEV_TEMP_TABLESPACE=${APP_DEV_TEMP_TABLESPACE}

