# Configuracao para criacao/gestao do usuario OWNER no ambiente DEV

# Conexao administrativa do ambiente DEV
flyway.url=${OWNER_DEV_ADMIN_URL}
flyway.user=${OWNER_DEV_ADMIN_USER}
flyway.password=${OWNER_DEV_ADMIN_PASSWORD}
flyway.jdbcProperties.internal_logon=SYSDBA
flyway.defaultSchema=${OWNER_DEV_ADMIN_USER}
flyway.table=flyway_history_owner_dev

flyway.locations=filesystem:./sql/migrations/db/projects/controle-financeiro/owner/owner-dev

# Placeholders usados pelos scripts SQL do OWNER DEV
flyway.placeholders.usuario_nome=${OWNER_DEV_USER}
flyway.placeholders.usuario_senha=${OWNER_DEV_PASSWORD}
flyway.placeholders.default_tablespace=${OWNER_DEV_DEFAULT_TABLESPACE}
flyway.placeholders.temp_tablespace=${OWNER_DEV_TEMP_TABLESPACE}
